### ISSUE TITLE
Make headings bold

### ISSUE THREAD

**Issue by jlblcc** [USFWS/alaska-region-metadata-guide#22]
Readability is improved with styled headings, otherwise sections all blend together.

Here's the PR: #21

Removing these line have the same effect:

```css
h1, h2, h3, h4, h5, h6 {
  font-weight: 600;
}
```
